### ISSUE TITLE
setting new Target positions

### ISSUE THREAD

**Issue by trerobotics** [agentx1118/ftc_app-master#1]
when setting a new target position you need to add the amount you want to rotate to the current position because the encoders do not reset after they rotate. So if your encoders have a resolution of 1440 and you rotate twice, the encoder position would be 2880. So when trying to set the position of an encoder, do setTargetPosition(encoder.getCurrentPosition + newRotationValue).

**Comment by agentx1118** [comment]
This was already done in some places, but we added it in a few other places in our OpMode in order to set boundaries for the arm.
